# Generated by Django 4.2.9 on 2024-01-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='job',
            field=models.CharField(max_length=50, null=True, verbose_name='직무'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(max_length=50, null=True, verbose_name='회원 닉네임'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='year',
            field=models.IntegerField(null=True, verbose_name='출생년도'),
        ),
    ]
