# Generated by Django 4.2.9 on 2024-02-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_job_usermodel_nickname_usermodel_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='generation',
            field=models.CharField(max_length=50, null=True, verbose_name='시대'),
        ),
    ]
