# Generated by Django 4.2.9 on 2024-08-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_first_login',
            field=models.BooleanField(default=True, verbose_name='최초 로그인 여부'),
        ),
    ]
