# Generated by Django 4.2.9 on 2024-08-06 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_is_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithdrawalReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='탈퇴 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_reasons', to=settings.AUTH_USER_MODEL, verbose_name='소셜사용자')),
            ],
            options={
                'verbose_name_plural': '탈퇴 사유',
                'db_table': 'user_withdrawal_reasons',
                'managed': True,
            },
        ),
    ]
