# Generated by Django 4.2.9 on 2024-08-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userwithdrawalreason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwithdrawalreason',
            name='user',
        ),
        migrations.AddField(
            model_name='userwithdrawalreason',
            name='social_id',
            field=models.CharField(default='', max_length=100, verbose_name='소셜사용자_id'),
        ),
    ]
