# Generated by Django 5.0 on 2024-01-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('emoji', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('delete_yn', models.CharField(default='N', max_length=1)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
