# Generated by Django 4.2.9 on 2024-01-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_answer_user_id_alter_block_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
