# Generated by Django 4.2.9 on 2024-01-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_answer_select_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='select_question',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
