# Generated by Django 4.2.9 on 2024-02-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_alter_block_update_at_alter_question_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='select_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_b',
        ),
        migrations.AddField(
            model_name='answer',
            name='user_choice',
            field=models.CharField(max_length=1, null=True, verbose_name='사용자 응답'),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_a',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_b',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='blocked_user_id',
            field=models.CharField(verbose_name='차단된 사용자'),
        ),
        migrations.AlterField(
            model_name='block',
            name='user_id',
            field=models.CharField(max_length=100, verbose_name='차단하는 사용자'),
        ),
    ]
