# Generated by Django 4.2.9 on 2024-08-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_alter_question_choice_a_alter_question_choice_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='emoji',
            field=models.CharField(max_length=20),
        ),
    ]
